create table public.refresh_tokens
(
    id                 bigserial generated by default as identity
        primary key,
    client_ip          varchar(45),
    client_type        varchar(255),
    created_at         timestamp(6) with time zone not null,
    device_fingerprint varchar(255),
    expiry_date        timestamp(6) with time zone not null,
    is_active          boolean                     not null,
    last_used_at       timestamp(6) with time zone,
    refresh_count      integer,
    refresh_token      varchar(255)
        constraint uk1yihy5j142kjit22kgccjixro
            unique,
    revoked_at         timestamp(6) with time zone,
    user_agent         varchar(255),
    user_id            bigserial
        constraint fk_refresh_tokens_users
            references users (id)
);